n=str(input("primul cuvant: "))
m=str(input("al doilea cuvant: "))
l=str(input("al treilea cuvant: "))
p=str(input("al patrulea cuvant: "))
print(n)
print(m)
print(l)
print(p)
print(n+" "+m+" "+l+" "+p+".")